In [1]:
pip install torch -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple

Looking in indexes: https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
  Using cached https://mirrors.tuna.tsinghua.edu.cn/pypi/web/packages/26/9f/ad63fc0248c5379346306f8668cda6e2e2e9c95e01216d2b8ffd9ff037d0/typing_extensions-4.12.2-py3-none-any.whl (37 kB)
  Using cached https://mirrors.tuna.tsinghua.edu.cn/pypi/web/packages/b2/fe/81695a1aa331a842b582453b605175f419fe8540355886031328089d840a/sympy-1.13.1-py3-none-any.whl (6.2 MB)
  Attempting uninstall: typing-extensions
    Found existing installation: typing-extensions 3.10.0.2
    Can't uninstall 'typing-extensions'. No files were found to uninstall.
  Attempting uninstall: sympy
    Found existing installation: sympy 1.9
    Can't uninstall 'sympy'. No files were found to uninstall.
Note: you may need to restart the kernel to use updated packages.


In [3]:
import torch

Ones tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.4592, 0.0219],
        [0.7521, 0.2091]]) 



In [4]:
data=[[1,2],[3,4]]
x_data=torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [ ]:
import torch
import numpy as np

In [7]:
data=[[1,2],[3,4]]
np_array=np.array(data)
x_np=torch.from_numpy(np_array)
x_np

NameError: name 'np' is not defined

In [ ]:
#由其他张量间接创建

In [6]:
data=[[1,2],[3,4]]
x_data=torch.tensor(data)
x_data

x_ones=torch.ones_like(x_data)
print(f"Ones tensor: \n {x_ones} \n")
x_rand=torch.rand_like(x_data,dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7687, 0.0115],
        [0.6940, 0.1165]]) 



In [ ]:
#创建常数张量